project:
  type: website

website:
  title: "Liang's Blogs"
  navbar:
    right:
      - about.qmd
      - cv.qmd
      - cv-cn.qmd
      - icon: github
        href: https://github.com/psychelzh
      - icon: twitter-x
        href: https://x.com/psychelzh
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css

editor: visual
