project:
  type: website

website:
  title: "Liang's Blogs"
  navbar:
    right:
      - about.qmd
      - cv.qmd
      - cv-cn.qmd
      - icon: github
        href: https://github.com/psychelzh
      - icon: twitter
        href: https://twitter.com/psychelzh
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

# freeze computational output
# (see https://quarto.org/docs/projects/code-execution.html#freeze)
execute:
  freeze: true
