---
title: "个人简历"
format:
  html:
    toc: true
  pdf:
    author: 张亮
    pdf-engine: weasyprint
css: cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
邮箱: psychelzh\@outlook.com <br> 个人网站: <https://psychelzh.github.io/> <br> Github: <https://github.com/psychelzh>
:::

## 教育经历

**博士 -- 认知神经科学** <br> *北京师范大学* [*2019年9月 --- 2024年7月*]{.cvdate}

-   博士论文：一般认知能力的认知与神经机制：来自测量学和脑网络的证据
-   指导老师：薛贵教授

**硕士 -- 认知神经科学** <br> *北京师范大学* [*2014年9月 --- 2017年6月*]{.cvdate}

-   硕士论文：儿童执行功能的结构与发展研究
-   毕业时被评为北京市优秀毕业生

**本科 -- 统计学** <br> *北京师范大学* [*2009年9月 --- 2013年6月*]{.cvdate}

-   毕业时成绩年级前5%
-   GPA: 3.7/4.0

## 项目经历

**国自然面上重点项目《学习与记忆终生发展的机制与干预》** <br> *参与人* [*2017年8月 --- 2022年7月*]{.cvdate}

-   负责设计与开发实验任务，实现互联网测评系统
-   负责行为数据分析，并参与撰写项目结题报告

**参与国自然面上重点项目《熟能生巧:记忆练习效应的神经机制及应用》** <br> *参与人* [*2014年9月 --- 2015年7月*]{.cvdate}

-   负责行为数据的采集工作，实现数据的自动化收集
-   负责生成自动化数据分析报告，并进行数据可视化

## 发表论文 {style="page-break-before: always"}

**Zhang, L.**, Feng, J., Xue, G*. (In preparation). The structure of human cognitive abilities: A study with comprehensive cognitive tasks.

Sheng, J.#, **Zhang, L.**#, Xue, G*. (In preparation). Shared and individualized representational transformations support episodic memory formation.

**Zhang, L.**, Feng, J., Liu, C., Hu, H., Zhou, Y., Yang, G., Peng, X., Li, T., Chen, C., & Xue, G*. (2024). Improved estimation of general cognitive ability and its neural correlates with a large battery of cognitive tasks. **Cerebral Cortex**, 34(2), bhad510. https://doi.org/10.1093/cercor/bhad510 (IF: 3.7, SCI二区)

Sheng, J., Wang, S., **Zhang, L.**, Liu, C., Shi, L., Zhou, Y., Hu, H., Chen, C., & Xue, G*. (2023). Intersubject similarity in neural representations underlies shared episodic memory content. **Proceedings of the National Academy of Sciences**, 120(35), e2308951120. https://doi.org/10.1073/pnas.2308951120 (IF: 11.1, SCI一区)

Feng, J., **Zhang, L.**, Chen, C., Sheng, J., Ye, Z., Feng, K., Liu, J., Cai, Y., Zhu, B., Yu, Z., Chen, C., Dong, Q., & Xue, G*. (2022). A cognitive neurogenetic approach to uncovering the structure of executive functions. **Nature Communications**, 13(1), 4588. https://doi.org/10.1038/s41467-022-32383-0 (IF: 16.6, SCI一区)

Sheng, J., **Zhang, L.**, Liu, C., Liu, J., Feng, J., Zhou, Y., Hu, H., & Xue, G*. (2022). Higher-dimensional neural representations predict better episodic memory. **Science Advances**, 8(16), eabm3829. https://doi.org/10.1126/sciadv.abm3829 (IF: 13.6, SCI一区)

\# 共同第一作者；* 通讯作者

## 会议海报

**Zhang, L.**, Xue, G. The neural substrates of general cognitive ability based on multiple cognitive tasks. Poster presented at the Annual Meeting of the Society for Neuroscience, November 2023, Washington, DC. USA.

## 专业技能

-   **编程语言**：R，Python，Matlab
-   **统计分析**：机器学习，线性混合效应模型、结构方程模型和贝叶斯统计建模等
-   **脑成像技术**：熟悉磁共振成像技术，会独立完成数据预处理与脑网络建模分析

::: {.no-print}
<details>Created based on tutorial of <https://www.cynthiahqy.com/posts/cv-html-pdf/></details>
:::
